{
 "title": "NYC Taxi API",
 "panels": [
  {
   "title": "Model Loaded",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "targets": [
    { "expr": "model_loaded" }
   ]
  },
  {
   "title": "Request Rate (/predict)",
   "type": "timeSeries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 6 },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Error Rate (/predict)",
   "type": "timeSeries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(prediction_errors_total[1m])"
    }
   ]
  },
  {
   "title": "Latency p95 (s)",
   "type": "timeSeries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prediction_request_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}